# Generated by Django 5.1.3 on 2024-12-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_users_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
